name: flutter_clean_solid_tdd_designpatterns
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  provider: ^6.0.2
  equatable: 2.0.3
  get: 4.6.1
  flutter_secure_storage: ^5.0.2
  localstorage: ^4.0.0+1
  carousel_slider: 4.0.0
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.2
  mocktail: 0.2.0
  faker: 2.0.0
  network_image_mock: 2.0.1
    
flutter:
  uses-material-design: true
  
  assets:
    - lib/ui/assets/
 
flutter_lints: ^1.0.0
flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android.png
  image_path_ios: lib/ui/assets/icon/ios.png
  adaptive_icon_background: lib/ui/assets/icon/background.png
  adaptive_icon_foreground: lib/ui/assets/icon/foreground.png
